# must be unique in a given SonarQube instance
sonar.projectKey=proyecto-react

# --- optional properties ---
# defaults to project key
sonar.projectName=Proyecto React

# defaults to 'not provided'
sonar.projectVersion=0.0.0

# Path is relative to the sonar-project.properties file. Defaults to .
sonar.sources=src

# Archivos y carpetas a excluir del análisis
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.test.js,**/*.test.jsx,**/*.config.js

# Archivos de prueba
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx

# Configuración para JavaScript/TypeScript
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# SOLO si usas JS/TS y NO tienes Node instalado en PATH
# Si ya tienes Node instalado, puedes borrar esta línea
sonar.nodejs.executable=C:\\Program Files\\nodejs\\node.exe

# Default SonarQube server
sonar.host.url=http://localhost:9000

# Token de autenticación (REEMPLAZA esto)
sonar.token=squ_9fc67399cc84c25c850fc1aea9f3459ff39b7243

# Encoding of the source code
sonar.sourceEncoding=UTF-8